### PR TITLE
Add landscape analysis

### PR DESCRIPTION
**Pull request by effigies**
Need to go do dinner, but here's a pass at landscape analysis. I did not really take anything from #10. It's possible we should consider talking about ITK as a direct comparison to nibabel, but I focused more on the suites, and ended up pretty close to the word limit covering what I thought were the main points.

### CODE REVIEW

**Comment by effigies** [comment]
Possibly another useful tidbit: According to `pypinfo -d 180 nibabel`, we've had >274k downloads off PyPI in the last 6 months.

**Comment by matthew-brett** [comment]
Where did you get the stats on number of repositories and packages depending on Nibabel?

**Comment by effigies** [comment]
If you check the right bar on GitHub... Can send a screenshot/link when I'm back on a computer.

**Comment by matthew-brett** [comment]
Ah yes - I see the "used by" repository number - but not the number of
packages.  Did I miss that?

**Comment by effigies** [comment]
Click on the counter, and there's a second tab.

**Comment by matthew-brett** [comment]
Ah - right - but what is a "package"?

Libraries.io PyPI gives 46 dependent packages:
https://libraries.io/pypi/nibabel/dependents

**Comment by effigies** [comment]
I think it's independently named packages, as defined by name in setup.py, found on either PyPI or GitHub, but I don't know. GitHub hasn't been extremely forthcoming about its algorithms. I'm okay using the PyPI stats.

**Pull request merged**
